name: ci

on:
  push:
    branches: 
      - master
    
  pull_request_review:
    types:
      - submitted

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./root/Dockerfile
          context: ./root
          push: true
          tags: fanot/root-docker-image:latest
